name: Deploy Pages
permissions:
  contents: write
  pages: write
  id-token: write

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # 新增这一行，解决 Missing environment 报错
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4

      - name: 配置 Pages
        uses: actions/configure-pages@v5

      - name: 上传静态文件
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: 部署到 GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
